# This file contains the definition of a Kubernetes Secret object.
# It includes metadata such as the name of the secret and the data it contains.
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi


