apiVersion: v1
kind: Service
metadata:
  name: svc-ns1
  namespace: ns1
spec:
  selector:
    app: nginx
  # The selector must match the labels of the pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP


  